### PR TITLE
Support rake version 11.0 or higher＆rspec version 3.4.0 or higher

### PR DESCRIPTION
**Pull request by nyagato-00**
## What is this?
Following is a PR initiative that addresses the following content.
- `rake` version 11.0 or higher
- `rspec` version 3.4.0 or higher
- Increased the version of Ruby used in Travis CI. (Added Ruby 2.3 ~ 2.7)

## Why we worked on it
Because executing the rake command raised the following exception.
```$console
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00007f9801855958>
/Library/Ruby/Gems/2.6.0/gems/rspec-core-2.14.8/lib/rspec/core/rake_task.rb:118:in `initialize'
```
This is because the `last_comment` method has been removed from `Rake 11.0.1`.

Also because I wanted to ensure that it works well with the latest Ruby version.

The predictor is a very good product, but maintenance seemed to have stopped 😢 .
So I wanted to maintain this product and created a PR.

## About the test
In my branch, I am making sure that Travis CI succeeds with each Ruby version.
travis-ci org_github_nyagato-00_predictor (1)

https://travis-ci.org/github/nyagato-00/predictor

### CODE REVIEW

**Comment by nyagato-00** [comment]
@jhdavids8 
Sorry for the sudden message.
Hello.

I've been using predictor for my company's products for a while now.
I've been using predictor in our product for a while now, but it's not being maintained and I'm not sure if I'll be able to continue using it 😢.
I've written a patch to make predictor work with the latest Ruby and rspec/rake 🙋♂️.

I'd love for you to review the code here!

P.S.
I'm not sure about the support for Ruby after EOL 😅.
If possible, I would like to continue to maintain it myself.

**Comment by NevilleS** [comment]
Hey @nyagato-00!

I'm quite pleased to have seen your comment and PR. As you might have noticed, the company that created this project (Pathgather) was acquired so it's not really being maintained there any more. I'd gladly help transfer this gem over to you as the maintainer if you're able to give it a good home!

**Comment by nyagato-00** [comment]
Hello, @NevilleS.

Thanks for the great news!

> As you might have noticed, the company that created this project (Pathgather) was acquired so it's not really being maintained there any more.

I'm aware that this project is not currently being maintained.

> I'd gladly help transfer this gem over to you as the maintainer if you're able to give it a good home!

All right.
This gem is very good.
So I'd like to take over the maintenance of it.

Best regards!

**Comment by NevilleS** [comment]
Hey @nyagato-00, I've moved the repo over to me now, so we can finish this by:
1. Transferring ownership of the GitHub repo to you as the owner
2. Adding you as the owner on rubygems.org so you can publish new releases

Can you create a rubygems.org account (if you don't have one) and let me know the email address you use for that?

**Comment by nyagato-00** [comment]
Hey, @NevilleS.

Thanks for getting this gem ready for transfer!

Here's my rubygems.org account.

URL: https://rubygems.org/profiles/nyagato_00
Email: nyagato.eva@gmail.com



Best regards!

**Comment by NevilleS** [comment]
Alright- it turns out GitHub won't let me transfer it to you yet, since nyagato-00/predictor - your fork - already exists:
image

Looks like you'll have to delete that before I can fully hand over the keys 😄

In the meantime, I've also invited you to be an owner on rubygems, which you can accept when you're ready

Let me know when I can try the repo transfer again!

**Comment by nyagato-00** [comment]
Hey, @NevilleS.

I'm sorry I didn't delete my forked repositories! 🙇‍♂️ 

I have removed predictor from my repository.
I think I can try to transfer repositories!

Also, I'm now the owner of rubygems!
https://rubygems.org/profiles/nyagato_00

Thanks!

**Comment by NevilleS** [comment]
OK, transfer requested... you can accept on your end and then predictor will officially be yours to maintain 😁

**Comment by nyagato-00** [comment]
Hey, @NevilleS.

Thank you!!! 😆
I just ACCEPTED it now.
I'll maintain it from now on 💪.

**Comment by NevilleS** [comment]
Congrats 😁. Treat it well! You should be able to merge your own PRs now. Let me know if you have any trouble publishing to rubygems.

Cheers!

**Pull request merged**
